name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Deploy to Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "cvpdmk8dl3ps7380uqtg", "clearCache": true}' \
            https://api.render.com/v1/services/cvpdmk8dl3ps7380uqtg/deploys)

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Render deployment failed. Response code: $RESPONSE"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Render deployment triggered successfully."
          fi

      # Notify deployment success
      - name: Notify Deployment
        if: success()
        run: echo "Deployment to Render completed successfully."
