name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to Render
      - name: Deploy to Render
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            https://api.render.com/deploy/srv-cvpdmk8dl3ps7380uqtg?key=-D7KtupNAaU)

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Render deployment failed. Response code: $RESPONSE"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Render deployment triggered successfully."
          fi

      # Notify deployment success
      - name: Notify Deployment
        if: success()
        run: echo "Deployment to Render completed successfully."
